### ISSUE TITLE
Total images not functioning. (discord.py)

### ISSUE THREAD

**Issue by ShibeShoop** [LordOfPolls/Rule34-API-Wrapper#12]
```
Rule34 = rule34.Sync()
total_images = Rule34.totalImages(tags)
print(total_images)
```
Throws this error:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python 3.8\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Python 3.8\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Python 3.8\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: This event loop is already running
D:\Python 3.8\lib\asyncio\events.py:81: RuntimeWarning: coroutine 'Rule34.totalImages' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

```

**Comment by LordOfPolls** [comment]
If you're using this API with discord.py, you shouldn't use `rule34.Sync()`, instead use `rule34.Rule34([your event loop])`. 

To explain, discord.py is asynchronous, so its best practice to use asynchronous code. As such this API wrapper has been programmed to work asynchronously, however, `rule34.Sync()` is there for people who aren't coding in an asynchronous environment, ie a command line app, not a bot
