### ISSUE TITLE
when downloading finished it crashes

### ISSUE THREAD

**Issue by technomooney** [LordOfPolls/Rule34-API-Wrapper#14]
i get a `AttributeError: module 'os' has no attribute 'startfile'`
at the end of the running of the program... 
with a full trace of 
```python3
Traceback (most recent call last):
  File "r34downloader.py", line 205, in <module>
    main.menu()
  File "r34downloader.py", line 193, in menu
    self.download(images)
  File "r34downloader.py", line 146, in download
    os.startfile(self.downloadLocation)
AttributeError: module 'os' has no attribute 'startfile'
```
i even installed the api wrapper from the github and it didn't help. 

i assume it is trying to open a "menu" of some sorts... it works fine other than that....

**Comment by technomooney** [comment]
just realised this should be in the downloader github...
