### ISSUE TITLE
getImages() outputting coroutine instead of rule34

### ISSUE THREAD

**Issue by lucas-fine** [LordOfPolls/Rule34-API-Wrapper#23]
I'm making a discord bot witch are asynchronous and the `getImages()` function is outputting coroutines so I can't get URL of the images

```
import discord
import rule34 as r34
import random as RNG
import urllib.request
import asyncio

client = discord.Client()
r34 = r34.Rule34(client.loop)

global post
post = ""

def img(tag):
    global post
    post = r34.getImages(singlePage=True, OverridePID=RNG.randint(1,100), tags=tag)
    print(post)

@client.event
async def _gatherPosts(do_videos, do_images, tag, ID, r34):
    await img(tag)

    # process this page
    video = (post.file_url.endswith("mp4") or post.file_url.endswith("webm"))  # is this a video?
    if do_images or do_videos:
        if do_videos and video:
            postList = post
        if do_images and not video:
            postList = post
    return urllib.request.urlretrieve(postList.file_url, ID + ".jpg")

@client.event
async def on_message(message):
    if message.mention_everyone:
        channel = message.channel
        await channel.send("shut the fuck up")

    if message.content.startswith("?p"):
        channel = message.channel
        await _gatherPosts(True, True, message.content.split(), message.id, r34)
        await channel.send('Say hello!')

client.run('TOKEN')
```
the terminal output
```
<coroutine object Rule34.getImages at 0x7f15e1c2d3b8>
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/lj_fin/.local/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "schmeckle.py", line 39, in on_message
    await _gatherPosts(True, True, message.content.split(), message.id, r34)
  File "schmeckle.py", line 20, in _gatherPosts
    await img(tag)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by LordOfPolls** [comment]
Hi there, I would suggest you look into how async works in Python. Coroutines are like functions, but run in async (see https://discordpy.readthedocs.io/en/latest/faq.html#what-is-a-coroutine).
All of rule34's functions are coroutines (unless you use the sync class). So you need to run ``await getImages(args)`` in order to use them. They are returning coroutine objects because they aren't executing, only returning what they are. Its also worth noting you cant run a coroutine from a function without using some sort of wrapper. 

Also. i would **strongly** suggest you dont use urllib with an async project, as it will block your main thread and stop the bot responding while it executes (se: https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean)
